version: '2'
services:
    kukulkan-app:
        image: kukulkan
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kukulkan-mysql:3306/kukulkan?useUnicode=true&characterEncoding=utf8&useSSL=false
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kukulkan-mysql:
        extends:
            file: mysql.yml
            service: kukulkan-mysql
